"""note summary fields

Revision ID: afad6ea87a2a
Revises: 7faef8e66c38
Create Date: 2026-10-03 12:28:27.093808

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "afad6ea87a2a"
down_revision: str | Sequence[str] | None = "7faef8e66c38"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notes", sa.Column("summary", sa.String(length=200), nullable=True))
    op.add_column("notes", sa.Column("tags", sa.JSON(), nullable=True))
    op.add_column("notes", sa.Column("sentiment", sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notes", "sentiment")
    op.drop_column("notes", "tags")
    op.drop_column("notes", "summary")
    # ### end Alembic commands ###
